// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package accounts

// _Entity represents all types with @key
type _Entity interface {
	Is_Entity()
}

type Entity struct {
	FindUserByID *User `json:"findUserByID"`
}

type User struct {
	ID       string  `json:"id"`
	Name     *string `json:"name"`
	Username *string `json:"username"`
}

func (User) Is_Entity() {}
