// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package inventory

// _Entity represents all types with @key
type _Entity interface {
	Is_Entity()
}

type Entity struct {
	FindProductByUpc *Product `json:"findProductByUpc"`
}

type Product struct {
	Upc              string `json:"upc"`
	Weight           *int   `json:"weight"`
	Price            *int   `json:"price"`
	InStock          *bool  `json:"inStock"`
	ShippingEstimate *int   `json:"shippingEstimate"`
}

func (Product) Is_Entity() {}
