// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package accounts

type Product struct {
	Upc     string    `json:"upc"`
	Reviews []*Review `json:"reviews"`
}

func (Product) IsEntity() {}

type User struct {
	ID       string    `json:"id"`
	Username *string   `json:"username"`
	Reviews  []*Review `json:"reviews"`
}

func (User) IsEntity() {}
