// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package accounts

// _Entity represents all types with @key
type _Entity interface {
	Is_Entity()
}

type Entity struct {
	FindProductByUpc *Product `json:"findProductByUpc"`
}

type Product struct {
	Upc    string  `json:"upc"`
	Name   *string `json:"name"`
	Price  *int    `json:"price"`
	Weight *int    `json:"weight"`
}

func (Product) Is_Entity() {}
